remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Anna Soroka
<br><br>
<img src="./assets/1.jpg" width="250" height="250">]
description: I have 10 years of professional experience in the field of price management, leveraging cutting-edge data analytics. Additionally, I have amassed two years of commercial experience working with Azure Databricks and Python. My professional journey encompasses three years of service with a prominent consulting firm Simon-Kucher&Partner, followed by a tenure with Shell retail. I have also provided my expertise in advisory capacities for price management start-up.
