remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Anna Soroka

<img src="./assets/1.jpg" width="300" height="400">]
description: [I have 8 years of professional experience in price management based on advanced data analytics and 2 years commercial work with big data (Azure Databricks, python). I worked 3 years in consulting firm Simon-Kucher&Partners, followed by work for Shell (downstream, retail) and advisory for price management start-up.<br><br> I'm open for new opportunities in Data Science field.]
