remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Anna Soroka - Data Science projects]
description: [The purpose of this site is to demonstrate example Data Science projects]
